var felsefe = [
    {"başlık":"ÜTOPYA","detay":"Zihinde tasarlanan ve gerçekleşmesi mümkün olmayan hayalidevlet tasarımlarıdı"},
    {"başlık":"FENOMEN","detay":"Duyularla algılanabilen şey veya şeyler."},
    {"başlık":"ARKHE","detay":"İlk neden. Filozofların her şeyin kendisinden türediğini dilegetirdikleri bir ilk madde, fikir."},
    {"başlık":"ÜTOPDOGMACILIK/DOGMATİZMYA","detay":" Kuşkuyu reddeden felsefe veya din.Öne sürülen öğreti ve ilkeleri eleştirmeden kabul eden felsefi anlayış."},
    {"başlık":"DÜALİZM","detay":" İkicilik. Örneğin madde-ruh gibi. Ontolojik olarak varlığın“bir” değil, birden fazla olması."},
    {"başlık":"EREK ","detay":"Amaç."},
    {"başlık":"GENEL-GEÇER","detay":"Zaman ve mekana bağlı olmayan, her zaman ve heryerde geçerli olan. Genel-geçer bilgi kastedildiği zaman da her zamangeçerli olan bilgi anlamını taşır."},
    {"başlık":"İDE","detay":"Fikir anlamında kullanılır. İde/idea şeklinde de gelebilir."},
    {"başlık":"KOSMOS/KOZMOZ","detay":"Evren demektir. Kendi içinde uyumlu evren."},
    {"başlık":"KURAM(TEORİ)","detay":"Hipotezin deney ve gözlem yoluyla kısmendoğrulanmasıdır."},
    {"başlık":"MATERYALİZM", "detay":"(Maddecilik ) Varlığın sadece dokunabildiğimizmaddelerden ibaret olduğunu savunan düşünce."},
    {"başlık":"METAFİZİK/DOĞA ÖTESİ", "detay":"Fizik ötesi, algılanabilen veyaduyumsanabilen dünya dışındaki şey veya şeylerin dünyası. Örneğintin/ruh, Tanrı gibi kavramlar birer metafizik kavramlardır."},
    {"başlık":"MİTOLOJİ", "detay":"İnsan ve evrenle ilgili olayların doğaüstü güçlerle ve dinselinançlarla(efsane) hayal gücüne dayalı açıklamalardır."},
    {"başlık":"MONİZM", "detay":"Var olan gerçekliğin “tek” olması. Örneğin varlık maddedir,varlık idedir gibi"},
    {"başlık":"NORMATİF", "detay":"Kural koyucu anlamına gelir. Belli bir kural taşıyan."},
    {"başlık":"NUMEN", "detay":" Nesnenin, algıların dışında kalan özü (Kant)"},
    {"başlık":"OBJEKTİF/NESNEL", "detay":"Kişiden kişiye değişmeyen. Yani nesnede oluşan,öznenin duygu ve düşüncelerine değil, nesnenin gerçekliğine dayanan."},
    {"başlık":"OLGUSAL", "detay":"Nesnelere dayanan. Olgu=nesne"},
    {"başlık":"PARADİGMA", "detay":" Değerler dizisi, model, yaklaşım, yeni bir görüş penceresi gibi anlamlara gelir. Bilim adamlarının bir döneme hakimolmuş, bir dönem geçerliliğini korumuş bilimsel düşünce, bakış açılarıdır.Pradigmalar zaman içerisinde değişikliğe uğrayabilir."},
    {"başlık":"REFLEKSİF", "detay":"Bir şeyin kendi kendisine geri dönmesi. Kendine geridönen, bu niteliğe sahip olan."},
    {"başlık":"RÖLATİVİZM/GÖRECELİLİK", "detay":"Bilginin veya her hangi bir şeyinkişiden kişiye göre değişeceğini dile getiren kavram."},
    {"başlık":"SUBJEKTİF/ÖZNEL", "detay":"Kişiden kişiye değişen şeyler. Yani öznedeoluşan, nesnelerin gerçekliğine değil, bireyin düşünce ve duygularınadayanan."},
    {"başlık":"TEMELLENDİRME", "detay":"Öne sürülen bir düşüncenin doğruluğunungerekçelerini göstermek."},
    {"başlık":"TUTARLILIK", "detay":"Mantık Kurallarına Uygunluk"},
    {"başlık":"EVRENSEL", "detay":"Herkese Açık."},
    {"başlık":"TÖZ/CEVHER", "detay":"Öznede değil, kendinde var olan. Bağımsızca kendiiçinde var olan. Yani değişen şeylere karşı değişmeyen. Var oluşu için başka hiçbir şeye ihtiyaç duymayan."},
    {"başlık":"TÜMDENGELİM/DEDÜKSİYON", "detay":"İnsan aklının genelden özele veya bütünden parçaya doğru yapmış olduğu akıl yürütmedir."},
    {"başlık":"TÜMEVARIM/ENDÜKSİYON", "detay":"İnsan aklının özelden genele veya parçadan bütüne doğru yapmış olduğu akıl yürütmedir"},
    {"başlık":"ETİK ", "detay":"ahlakın temellerini inceleyen felsefe dalı."},
    {"başlık":"HAZCILIK ", "detay":"Hazzı yaşamın temeli veya amacı sayan ahlaksistemi"},
    {"başlık":"KADERCİLİK VE YAZGICILIK", "detay":"Bütün olanların önceden belirlendiğini öne süren öğreti"},
    {"başlık":"POZİTİVİZM ", "detay":"(olguculuk): bütün felsefi ve bilimsel çalışmaların, yalnızdeneyle doğrulanabilen gerçek olguların çerçevesi içinde yürütülmesiniöne süren felsefi öğreti."},
    {"başlık":"PRAGMATİZM", "detay":"bir şeyin gerçekleşme olasılıklarını, gerçeğin ölçütüolarak kabul eden öğreti."},
    {"başlık":"ATEİZM", "detay":"Tanrı’nın varlığını reddeden öğreti"},
    {"başlık":"İMGELEME", "detay":"Düşünülen durum ya da olayın imgesinin (hayalinin –görüntüsünün) zihinde canlandırılmasıdır"},
    {"başlık":"İNDETERMİNİZM ", "detay":"Bu görüşe göre, insan ahlaki eylemleri ile ilgilikararları özgürce belirler"},
    {"başlık":"OLİGARŞİ ", "detay":"Hakimiyetin bir gruba veya bir sınıfa ait olduğu devletyönetim şekli"},
    {"başlık":"RASYONALİZM ", "detay":"Rasyonalizme göre, zorunlu, kesin vegenel geçer bilgilere ancak akılla ulaşılır"},
    {"başlık":"SEPTİSİZM", "detay":"(Kuşkuculuk, Şüphecilik) Gerçekliğin özünü bilmenin olanaklı olmadığını ileri süren öğretiler bütünüdür."},
    {"başlık":"TEOLOJİ", "detay":"Evrende olup biten her şeyi tanrıya bağlayan görüştür."},
    {"başlık":"VAROLUŞCULUK", "detay":"Varoluşçuluk, insanınyaşamını kendisinin kurması açısından özgür olduğunu savunur."},
    {"başlık":"ONTOLOJİ", "detay":"Varlıkla ilgili sorunların tartışıldığı metafizik alanıontolojidir"},
    {"başlık":"FELSEFE BİLGİSİ", "detay":"Özne (sübje) nin, evreni, insanı, evrende insanınyeri ve kaderini salt düşünce temelinde sistemli olarak açıklama veyorumlama çabasına felsefi bilgi denir"},
    {"başlık":"ENTÜİSYONİZM ", "detay":"Kesin ve değişmez bilgilere sezgiaracılığı ile ulaşılabileceğini savunan akım enstüisyonizmdir"},
    {"başlık":"DOĞRULUK ", "detay":"Hakikat) : Bilginin bilgi konusu ile tam uygunluk içinde bulunmasıdır"},
    {"başlık":"ANARŞİZM", "detay":"Toplumsal yaşamı düzenleyen tüm kurum ve kurallarıreddeden anarşizm, doğal olarak ahlak kurallarının egemenliğini dereddeder"},
    {"başlık":"FELSEFE", "detay":"Bilgiyi Sevmek, Bilgiyi Aramak"},
    {"başlık":"EPİSTEMOLOJİ", "detay":"Bilgi Felsefesi"},
    {"başlık":"BİLGİ", "detay":"Özne ile nesnenin birleşmesi. Sonucu elde edilen üründür"},
    {"başlık":"EMPRİK BİLGİ", "detay":"Deneyimsel Bilgi"},
    {"başlık":"HUMANİZM", "detay":"İnsan Felsefesi"},
    {"başlık":"REALİZM", "detay":"Gerçekçilik "},
    {"başlık":"MEŞRUİYET", "detay":"Yasallık ( Hukuka Uygun )"},
    {"başlık":"SOSYALİZM", "detay":"Eşitliğe Dayalı Ekonomik Düzen"},
    {"başlık":"KAPİTALİZM", "detay":"Özgürlüğe Dayalı Ekonomik Düzen"},
    {"başlık":"LİBERALİZM", "detay":"Özgürlüğe Dayalı Yönetim Biçimi"},
    {"başlık":"KOMÜNİZM", "detay":"Eşitliğe Dayalı Yönetim Biçimi"},
    {"başlık":"A POSTERİORİ", "detay":"Deneyden sonra, onun ürünü olarak ortaya çıkan bilgi"},
    {"başlık":"A PRİORİ", "detay":"Her türlü tecrübeden önce, yalnız akla dayanılarak kabul olunan bilgi"},
    {"başlık":"LOGOS", "detay":"Söz, düşünce, kavram, akıl ve evrenin kanunu"},
    {"başlık":"ÖZ", "detay":"Bir şeyi o şey yapan özellik ya da yapı. Bu öz, bir şeyin ne olduğunuifade eder."},
    {"başlık":"TİN", "detay":"Öznenin duyusal yanıyla düşünsel yanını birbirinden ayırmaeğilimi, antikçağ Yunan düşüncesiyle başlar"},
    {"başlık":"TEOLOJİ", "detay":"Tanrıbilim demektir. Dine ilişkin olgu ve fenomenleri konualan ve dinle ilgili olarak geniş kapsamlı bir senteze ulaşmayı amaçlayandisiplin"},
    {"başlık":"EKLEKTİK ", "detay":"Çeşitli görüşlerden, sistemlerden alıntılar yaparak yeni birsistem oluşturma"},
    {"başlık":"AKT", "detay":"Suje ve obje arasında gerçekleşen bilinç etkinliğidir. Bilgi aktlarıalgılama, anlama ve açıklama şeklinde olabilir"},
    {"başlık":"SUJE", "detay":"ÖzNe"},
    {"başlık":"OBJE", "detay":"Nesne"},
    {"başlık":"SUBJEKTİF", "detay":"Öznel"},
    {"başlık":"OBJEKTİF", "detay":"Nesnel"},
    {"başlık":"AMPİRİZM", "detay":"Bilginin sadece duyumlardan geldiğine ve deney dışında hiçbir yoldan bilgi edinilemeyeceğine inanılan öğretidir"},
    {"başlık":"DETERMİNİZM", "detay":"Ahlaki seçimler dahil bütün olayları, özgür iradeyi ve insanın başka türlü davranabilmesi olanağını dışlayan, önceden var olan nedenler ile belirlendiğini savunan felsefi kuramdır."},
    {"başlık":"DİYALEKTİK", "detay":"Kavramlar arasındaki karşıtlık ilişkisinden yola çıkarak bunu doğruya varan süreçlerin açığa çıkarılmasında bir ilke olarak kullanan düşünme ve araştırma yoludur."},
    {"başlık":"DOGMATİZM", "detay":"Din ya da yetkelerce ileri sürülen düşünce ve ilkeleri kanıt aramaksızın ve eleştirmeksizin kabullenen anlayıştır."},
    {"başlık":"ELEŞTİRİCİLİK", "detay":"Kant’ın us ve bilginin sınırını ve olanaklarını saptamak üzere, özellikle dogmacılığın ve kuşkuculuğun karşısına koyduğu felsefe yöntemidir"},
    {"başlık":"ESTETİK", "detay":"Güzeli ve güzel sanatların doğasını inceleyen felsefe dalıdır."},
    {"başlık":"HİÇÇİLİK ", "detay":"Var olan görüşlere, değerlere ve düzene karşı çıkan; hiçbir değer tanımayan görüşlere verilen addır."},
    {"başlık":"NİHİLİZM", "detay":"Yalnızca bilimsel doğruları temel alır, sadece bilimin toplumsal sorunların üstesinden gelebileceğini ve bütün kötülüklerin cehaletten kaynaklandığını kabul eder."},
    {"başlık":"ONTOLOJİ", "detay":"Varlığı bütünüyle inceleyen felsefe dalıdır. Bir diğer ismi varlık bilimidir."},
    {"başlık":"AGNOSTİSİZM", "detay":"Bilinemezcilik-İnsanın, kendi deneyimleriyle elde ettiği olguların ötesinde hiçbir şeyin varlığını bilemeyeceğini ileri süren öğretidir. Agnostisizm hem bir terim, hem de felsefi kavram olarak Thomas Huxley tarafından ortaya atılmıştır."},
    {"başlık":"Eklektizm", "detay":"tek ve belli bir yönü olmayan, çeşitli felsefe akımlarından gerekli gördüğü şeyleri alarak bir araya toplayan bir felsefe anlaşılır."},
    {"başlık":"Enstürmantalizm", "detay":"Amerikan düşünürü pragmacı John Dewey'in kuramları alet sayan öğretisidir."},
    {"başlık":"FATALİZM", "detay":"Her şeyin alın yazısına göre önceden belirlenmiş olduğuna, insanın bu önceden belirlenmiş olan alın yazısını değiştiremeyeceğine inanan dünya görüşü."},
    {"başlık":"HEDONİZM", "detay":"Yaşamın anlamını hazda gören anlayış. Ahlaki eylemin amacını hazda bulan ahlak öğretisi."},
    {"başlık":"İDEALİZM", "detay":"Var olan her şeyi düşünceye bağlayan, düşünce dışında nesnel bir gerçekliğin var olduğunu kabul etmeyen felsefe öğretisi."},
    {"başlık":"KÜMÜLATİF", "detay":"Yığılımlı anlamına da gelir. Felsefi bilgi, bilimsel bilgi gibi önceden bilinen bir şeylerin üstüne ekleme yapmaz, kendi bildiklerini belirtir."},
    {"başlık":"KRİTİSİZM", "detay":"Eleştiricilik-Alman düşünürü Immanuel Kant'ın öğretisi...Kant'a göre felsefe araştırması, bir değerlendirme (eleştiri) olmalıdır."},
    {"başlık":"LİBERYARTALİZM", "detay":"İnsanın doğuştan getirdiği hakları paralelinde özgür olduğunu savunan özgürlükçü yaklaşımdır."},
    {"başlık":"METAFİZİK", "detay":"Fizik ötesi"},
    {"başlık":"MİMESİS", "detay":"Taklit; benzetme, örnek alınan şeyi yeniden yapma."},
    {"başlık":"OLUŞÇULUK", "detay":"Varlığı oluşa yani değişime dayalı açıklayan yaklaşım."},
    {"başlık":"ÖDEV AHLAKI", "detay":"Kant'ı ahlak görüşü. Ahlaki eylemde bulunmayı ahlak yasasına uyma olarak kabul eden öğreti."},
    {"başlık":"PANTEİZM", "detay":"Bir bütün olarak kavranan evrenin Tanrı ile özdeş olduğu ve evrende açığa çıkan bileşik töz, güçler ve yasalar dışında Tanrı olmadığı öğretidir."},
    {"başlık":"POLİTEİZM", "detay":"Çok tanrıcılık."},
    {"başlık":"SENSUALİZM", "detay":"Bilginin duyumdan geldiğini savunan öğreti."},
    {"başlık":"UTULİTARİZM", "detay":"Etikte bir eylemin doğruluğunu etkilediği kişilere getirdiği mutlulukla ölçen görüş."},
    {"başlık":"GERÇEKLİK", "detay":"var olan her şey demektir. Düşünceden bağımsız olarak zamanda ve mekanda yer kaplayan her şey gerçektir. Herhangi bir şeyin gerçekliği insan zihnine bağlı olmaksızın var olmasıdır."},
    {"başlık":"BİNYILCILIK", "detay":" belirli tipteki dinsel hareketlerin üyeleri tarafından benimsenen, yakın gelecekte, yeni bir çağın gelişini gösterecek olan yıkıcı değişmelerin gerçekleşeceği biçimindeki inançlardır."},
    {"başlık":"MUTLAK İDEALİZM", "detay":" Bir idealizm biçimi, mutlak idealizm, Hegel'in varlığın nihai olarak her şeyi kapsayan bir bütün olarak nasıl anlaşılır olduğuna dair açıklamasıdır."},
    {"başlık":"MONİZM", "detay":"ya da bircilik, her şeyin bir tek zorunluluğun, ilkenin, madde ve enerjiden olduğunu iddia eden veya tek bir tözden kaynaklandığını savunan felsefi görüş."},
    {"başlık":"DÜALİZM", "detay":"genellikle birbirine karşı çıkan iki temel kavramın var olduğuna dair ahlaki veya ruhsal inançtır. Hem geleneksel dinler hem de kutsal kitap dinleri dahil olmak üzere çeşitli dinlerden çeşitli görüşleri kapsayan şemsiye bir terimdir."},
    {"başlık":"SPİRİTÜALİZM", "detay":"Latince “ruh” anlamına gelen “spiritus” sözcüğünün sıfatı “spiritualis” sözcüğünden türetilmiş olup ruhçuluk anlamında kullanılmaktadır. Türkçede tinselcilik olarak da adlandırılmaktadır"},
];

 // Başlıkları alfabetik sıraya göre düzenle
 felsefe.sort((a, b) => a.başlık.localeCompare(b.başlık, "tr"));

// HTML listesi olarak göster
const felsefeListesi = document.getElementById("felsefe-listesi");
felsefe.forEach(item => {
const listItem = document.createElement("li");
listItem.innerHTML = `<h3><strong>${item.başlık}</strong></h3><p style="font-size: 18px;"> ${item.detay}</p>`;
felsefeListesi.appendChild(listItem);
});